spring:
  profiles:
    active: native
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///C:/Users/taq/Projects/microservices-demo/ms-config-properties/{application}/{profile},
            file:///C:/Users/taq/Projects/microservices-demo/ms-config-properties/global/{profile}
---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qtanmarc/microservices-demo
          search-paths:
            - "ms-config-properties/{application}/{profile}"
            - "ms-config-properties/global/{profile}"
          default-label: main