spring:
  profiles:
    active: native
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isilona/microservices/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
            - "ms-config-properties/global/{profile}"