spring:
  profiles:
    active: native
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:///C:/Users/taq/Projects/microservices-demo/ms-config-properties/{application}/{profile},
            file:///C:/Users/taq/Projects/microservices-demo/ms-config-properties/global/{profile}
---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qtanmarc/microservices-demo/
          search-paths:
            - "ms-config-properties/{application}/{profile}"
            - "ms-config-properties/global/{profile}"